export type MasterDataStorage = 'generic' | 'department' | 'team'
export type MasterDataCodePolicy = 'optional' | 'recommended' | 'required'
export type MasterDataExtraFields = 'none' | 'intake' | 'leadStatus'

export type MasterDataCategory = {
  key: string
  name: string
  group: string
  storage: MasterDataStorage
  codePolicy: MasterDataCodePolicy
  parentCategoryKey?: string
  extraFields: MasterDataExtraFields
}

export type MasterDataSeed = {
  categoryKey: string
  name: string
  code: string
  description?: string
  sortOrder: number
  isSystem?: boolean
  behaviorKey?: string
  parentCode?: string
  extras?: Record<string, string>
}

export const MASTER_DATA_CATEGORIES: MasterDataCategory[] = [
  { key: 'LEAD_SOURCE', name: 'Lead Source', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_STATUS', name: 'Lead Status', group: 'Lead Management', storage: 'generic', codePolicy: 'required', extraFields: 'leadStatus' },
  { key: 'LEAD_TYPE', name: 'Lead Type', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_PRIORITY', name: 'Lead Priority', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_QUALITY', name: 'Lead Quality', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_LOST_REASON', name: 'Lead Lost Reason', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_CLOSE_REASON', name: 'Lead Close Reason', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EDUCATION_LEVEL', name: 'Education Level', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ACADEMIC_BACKGROUND', name: 'Academic Background', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SUBJECT_FIELD', name: 'Subject/Field of Study', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'GRADING_SYSTEM', name: 'Grading System', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ENGLISH_TEST_TYPE', name: 'English Test Type', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ENGLISH_PROFICIENCY_LEVEL', name: 'English Proficiency Level', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'COUNTRY', name: 'Country', group: 'Study Abroad', storage: 'generic', codePolicy: 'required', extraFields: 'none' },
  { key: 'STATE_PROVINCE', name: 'State/Province', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'COUNTRY', extraFields: 'none' },
  { key: 'CITY', name: 'City', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'STATE_PROVINCE', extraFields: 'none' },
  { key: 'INTAKE', name: 'Intake', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', extraFields: 'intake' },
  { key: 'UNIVERSITY', name: 'University', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'COUNTRY', extraFields: 'none' },
  { key: 'COURSE_PROGRAM', name: 'Course/Program', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'UNIVERSITY', extraFields: 'none' },
  { key: 'STUDY_LEVEL', name: 'Study Level', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SERVICE_CATEGORY', name: 'Service Category', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SERVICE_TYPE', name: 'Service Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'SERVICE_CATEGORY', extraFields: 'none' },
  { key: 'PACKAGE_TYPE', name: 'Package Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CHARGE_TYPE', name: 'Charge Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DISCOUNT_TYPE', name: 'Discount Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ACTIVITY_TYPE', name: 'Activity Type', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'FOLLOW_UP_TYPE', name: 'Follow-up Type', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CONTACT_METHOD', name: 'Contact Method', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CONTACT_RESULT', name: 'Contact Result', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DEPARTMENT', name: 'Department', group: 'Employee', storage: 'department', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'TEAM', name: 'Team', group: 'Employee', storage: 'team', codePolicy: 'recommended', parentCategoryKey: 'DEPARTMENT', extraFields: 'none' },
  { key: 'DESIGNATION', name: 'Designation', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EMPLOYMENT_TYPE', name: 'Employment Type', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EMPLOYMENT_STATUS', name: 'Employment Status', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DOCUMENT_CATEGORY', name: 'Document Category', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DOCUMENT_TYPE', name: 'Document Type', group: 'Documents', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'DOCUMENT_CATEGORY', extraFields: 'none' },
  { key: 'DOCUMENT_STATUS', name: 'Document Status', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'REJECTION_REASON', name: 'Rejection Reason', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_METHOD', name: 'Payment Method', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_TYPE', name: 'Payment Type', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_STATUS', name: 'Payment Status', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'REFUND_REASON', name: 'Refund Reason', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
]

export const MASTER_DATA_CATEGORY_MAP = new Map(MASTER_DATA_CATEGORIES.map((item) => [item.key, item]))

export const MASTER_DATA_SEEDS: MasterDataSeed[] = [
  { categoryKey: 'LEAD_SOURCE', name: 'Meta', code: 'META', sortOrder: 1 },
  { categoryKey: 'LEAD_SOURCE', name: 'Website', code: 'WEBSITE', sortOrder: 2 },
  { categoryKey: 'LEAD_SOURCE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 3 },
  { categoryKey: 'LEAD_SOURCE', name: 'Referral', code: 'REFERRAL', sortOrder: 4 },
  { categoryKey: 'LEAD_SOURCE', name: 'Walk-in', code: 'WALK_IN', sortOrder: 5 },
  { categoryKey: 'LEAD_SOURCE', name: 'Phone', code: 'PHONE', sortOrder: 6 },
  { categoryKey: 'LEAD_SOURCE', name: 'Campaign', code: 'CAMPAIGN', sortOrder: 7 },
  { categoryKey: 'LEAD_SOURCE', name: 'Other', code: 'OTHER', sortOrder: 8 },
  { categoryKey: 'LEAD_STATUS', name: 'New', code: 'NEW', sortOrder: 1, isSystem: true },
  { categoryKey: 'LEAD_STATUS', name: 'Contacted', code: 'CONTACTED', sortOrder: 2 },
  { categoryKey: 'LEAD_STATUS', name: 'Counselling', code: 'COUNSELLING', sortOrder: 3 },
  { categoryKey: 'LEAD_STATUS', name: 'Interested', code: 'INTERESTED', sortOrder: 4 },
  { categoryKey: 'LEAD_STATUS', name: 'Offer Sent', code: 'OFFER_SENT', sortOrder: 5 },
  { categoryKey: 'LEAD_STATUS', name: 'Converted', code: 'CONVERTED', sortOrder: 6, isSystem: true, behaviorKey: 'converted' },
  { categoryKey: 'LEAD_STATUS', name: 'Closed', code: 'CLOSED', sortOrder: 7, isSystem: true, behaviorKey: 'closed' },
  { categoryKey: 'LEAD_STATUS', name: 'Lost', code: 'LOST', sortOrder: 8, isSystem: true, behaviorKey: 'lost' },
  { categoryKey: 'LEAD_TYPE', name: 'Student', code: 'STUDENT', sortOrder: 1 },
  { categoryKey: 'LEAD_TYPE', name: 'Guardian', code: 'GUARDIAN', sortOrder: 2 },
  { categoryKey: 'LEAD_PRIORITY', name: 'High', code: 'HIGH', sortOrder: 1 },
  { categoryKey: 'LEAD_PRIORITY', name: 'Medium', code: 'MEDIUM', sortOrder: 2 },
  { categoryKey: 'LEAD_PRIORITY', name: 'Low', code: 'LOW', sortOrder: 3 },
  { categoryKey: 'LEAD_QUALITY', name: 'Hot', code: 'HOT', sortOrder: 1 },
  { categoryKey: 'LEAD_QUALITY', name: 'Warm', code: 'WARM', sortOrder: 2 },
  { categoryKey: 'LEAD_QUALITY', name: 'Cold', code: 'COLD', sortOrder: 3 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Budget Issue', code: 'BUDGET', sortOrder: 1 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Changed Study Plan', code: 'STUDY_PLAN', sortOrder: 2 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 3 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Wrong Information', code: 'WRONG_INFO', sortOrder: 4 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Chose Another Agency', code: 'OTHER_AGENCY', sortOrder: 5 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Visa Concern', code: 'VISA', sortOrder: 6 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'No Response', code: 'NO_RESPONSE', sortOrder: 7 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Other', code: 'OTHER', sortOrder: 8 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Converted', code: 'CONVERTED', sortOrder: 1 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 2 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Duplicate', code: 'DUPLICATE', sortOrder: 3 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Invalid Lead', code: 'INVALID', sortOrder: 4 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Service Not Available', code: 'UNAVAILABLE', sortOrder: 5 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Other', code: 'OTHER', sortOrder: 6 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'SSC / O-Level', code: 'SSC', sortOrder: 1 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'HSC / A-Level', code: 'HSC', sortOrder: 2 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Diploma', code: 'DIPLOMA', sortOrder: 3 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Bachelor', code: 'BACHELOR', sortOrder: 4 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Master', code: 'MASTER', sortOrder: 5 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'PhD', code: 'PHD', sortOrder: 6 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Science', code: 'SCIENCE', sortOrder: 1 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Commerce', code: 'COMMERCE', sortOrder: 2 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Arts / Humanities', code: 'ARTS', sortOrder: 3 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Engineering', code: 'ENGINEERING', sortOrder: 4 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Business Studies', code: 'BUSINESS', sortOrder: 5 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Computer Science', code: 'CS', sortOrder: 1 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Business Administration', code: 'BBA', sortOrder: 2 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Accounting & Finance', code: 'AF', sortOrder: 3 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Nursing', code: 'NURSING', sortOrder: 4 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Civil Engineering', code: 'CIVIL', sortOrder: 5 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Data Science', code: 'DATA_SCIENCE', sortOrder: 6 },
  { categoryKey: 'GRADING_SYSTEM', name: 'GPA (4.0)', code: 'GPA_4', sortOrder: 1 },
  { categoryKey: 'GRADING_SYSTEM', name: 'GPA (5.0)', code: 'GPA_5', sortOrder: 2 },
  { categoryKey: 'GRADING_SYSTEM', name: 'Percentage', code: 'PERCENT', sortOrder: 3 },
  { categoryKey: 'GRADING_SYSTEM', name: 'CGPA', code: 'CGPA', sortOrder: 4 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'IELTS', code: 'IELTS', sortOrder: 1 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'TOEFL', code: 'TOEFL', sortOrder: 2 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'PTE', code: 'PTE', sortOrder: 3 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'Duolingo', code: 'DUOLINGO', sortOrder: 4 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Beginner', code: 'BEGINNER', sortOrder: 1 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Intermediate', code: 'INTERMEDIATE', sortOrder: 2 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Advanced', code: 'ADVANCED', sortOrder: 3 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 6.0', code: 'IELTS_60', sortOrder: 4 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 6.5', code: 'IELTS_65', sortOrder: 5 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 7.0', code: 'IELTS_70', sortOrder: 6 },
  { categoryKey: 'COUNTRY', name: 'Canada', code: 'CA', sortOrder: 1 },
  { categoryKey: 'COUNTRY', name: 'United Kingdom', code: 'UK', sortOrder: 2 },
  { categoryKey: 'COUNTRY', name: 'Australia', code: 'AU', sortOrder: 3 },
  { categoryKey: 'COUNTRY', name: 'USA', code: 'US', sortOrder: 4 },
  { categoryKey: 'COUNTRY', name: 'Germany', code: 'DE', sortOrder: 5 },
  { categoryKey: 'STATE_PROVINCE', name: 'Ontario', code: 'ON', sortOrder: 1, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'Alberta', code: 'AB', sortOrder: 2, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'British Columbia', code: 'BC', sortOrder: 3, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'England', code: 'ENG', sortOrder: 4, parentCode: 'UK' },
  { categoryKey: 'STATE_PROVINCE', name: 'New South Wales', code: 'NSW', sortOrder: 5, parentCode: 'AU' },
  { categoryKey: 'CITY', name: 'Toronto', code: 'TORONTO', sortOrder: 1, parentCode: 'ON' },
  { categoryKey: 'CITY', name: 'Ottawa', code: 'OTTAWA', sortOrder: 2, parentCode: 'ON' },
  { categoryKey: 'CITY', name: 'Calgary', code: 'CALGARY', sortOrder: 3, parentCode: 'AB' },
  { categoryKey: 'CITY', name: 'Vancouver', code: 'VANCOUVER', sortOrder: 4, parentCode: 'BC' },
  { categoryKey: 'CITY', name: 'London', code: 'LONDON', sortOrder: 5, parentCode: 'ENG' },
  { categoryKey: 'CITY', name: 'Sydney', code: 'SYDNEY', sortOrder: 6, parentCode: 'NSW' },
  { categoryKey: 'INTAKE', name: 'January 2027', code: 'JAN_2027', sortOrder: 1, extras: { startDate: '2027-01-01', endDate: '2027-01-31' } },
  { categoryKey: 'INTAKE', name: 'May 2027', code: 'MAY_2027', sortOrder: 2, extras: { startDate: '2027-05-01', endDate: '2027-05-31' } },
  { categoryKey: 'INTAKE', name: 'September 2027', code: 'SEP_2027', sortOrder: 3, extras: { startDate: '2027-09-01', endDate: '2027-09-30' } },
  { categoryKey: 'INTAKE', name: 'January 2028', code: 'JAN_2028', sortOrder: 4, extras: { startDate: '2028-01-01', endDate: '2028-01-31' } },
  { categoryKey: 'UNIVERSITY', name: 'University of Toronto', code: 'UOT', sortOrder: 1, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of Alberta', code: 'UOA', sortOrder: 2, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'McGill University', code: 'MCGILL', sortOrder: 3, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of British Columbia', code: 'UBC', sortOrder: 4, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of Manchester', code: 'UOM', sortOrder: 5, parentCode: 'UK' },
  { categoryKey: 'UNIVERSITY', name: 'University of Sydney', code: 'USYD', sortOrder: 6, parentCode: 'AU' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Computer Science', code: 'CS', sortOrder: 1, parentCode: 'UOT' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Software Engineering', code: 'SE', sortOrder: 2, parentCode: 'UOT' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Business Administration', code: 'BBA', sortOrder: 3, parentCode: 'MCGILL' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Data Analytics', code: 'DA', sortOrder: 4, parentCode: 'UBC' },
  { categoryKey: 'COURSE_PROGRAM', name: 'International Business', code: 'IB', sortOrder: 5, parentCode: 'UOM' },
  { categoryKey: 'STUDY_LEVEL', name: 'Undergraduate', code: 'UG', sortOrder: 1 },
  { categoryKey: 'STUDY_LEVEL', name: 'Postgraduate', code: 'PG', sortOrder: 2 },
  { categoryKey: 'STUDY_LEVEL', name: 'Diploma', code: 'DIPLOMA', sortOrder: 3 },
  { categoryKey: 'STUDY_LEVEL', name: 'Foundation', code: 'FOUNDATION', sortOrder: 4 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Study Abroad', code: 'STUDY_ABROAD', sortOrder: 1 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Language Prep', code: 'LANGUAGE', sortOrder: 2 },
  { categoryKey: 'SERVICE_TYPE', name: 'University Application', code: 'UNI_APP', sortOrder: 1, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'Visa Processing', code: 'VISA', sortOrder: 2, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'Counselling', code: 'COUNSELLING', sortOrder: 3, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'IELTS Coaching', code: 'IELTS', sortOrder: 4, parentCode: 'LANGUAGE' },
  { categoryKey: 'PACKAGE_TYPE', name: 'Standard', code: 'STANDARD', sortOrder: 1 },
  { categoryKey: 'PACKAGE_TYPE', name: 'Premium', code: 'PREMIUM', sortOrder: 2 },
  { categoryKey: 'PACKAGE_TYPE', name: 'VIP', code: 'VIP', sortOrder: 3 },
  { categoryKey: 'CHARGE_TYPE', name: 'File Opening Charge', code: 'FILE_OPENING', sortOrder: 1 },
  { categoryKey: 'CHARGE_TYPE', name: 'Service Charge', code: 'SERVICE', sortOrder: 2 },
  { categoryKey: 'CHARGE_TYPE', name: 'Application Fee', code: 'APP_FEE', sortOrder: 3 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Percentage', code: 'PERCENT', sortOrder: 1 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Fixed', code: 'FIXED', sortOrder: 2 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Early Bird', code: 'EARLY_BIRD', sortOrder: 3 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Call', code: 'CALL', sortOrder: 1 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Meeting', code: 'MEETING', sortOrder: 4 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Counselling', code: 'COUNSELLING', sortOrder: 5 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Note', code: 'NOTE', sortOrder: 6 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Call', code: 'CALL', sortOrder: 1 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Meeting', code: 'MEETING', sortOrder: 4 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Document Collection', code: 'DOCUMENTS', sortOrder: 5 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Payment Follow-up', code: 'PAYMENT', sortOrder: 6 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Counselling Follow-up', code: 'COUNSELLING', sortOrder: 7 },
  { categoryKey: 'CONTACT_METHOD', name: 'Phone', code: 'PHONE', sortOrder: 1 },
  { categoryKey: 'CONTACT_METHOD', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'CONTACT_METHOD', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'CONTACT_METHOD', name: 'In Person', code: 'IN_PERSON', sortOrder: 4 },
  { categoryKey: 'CONTACT_RESULT', name: 'Connected', code: 'CONNECTED', sortOrder: 1 },
  { categoryKey: 'CONTACT_RESULT', name: 'No Answer', code: 'NO_ANSWER', sortOrder: 2 },
  { categoryKey: 'CONTACT_RESULT', name: 'Interested', code: 'INTERESTED', sortOrder: 3 },
  { categoryKey: 'CONTACT_RESULT', name: 'Call Back Later', code: 'CALLBACK', sortOrder: 4 },
  { categoryKey: 'CONTACT_RESULT', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 5 },
  { categoryKey: 'CONTACT_RESULT', name: 'Wrong Number', code: 'WRONG_NUMBER', sortOrder: 6 },
  { categoryKey: 'DESIGNATION', name: 'Administrator', code: 'ADMINISTRATOR', sortOrder: 0, isSystem: true, description: 'Fixed system designation for root administrator' },
  { categoryKey: 'DESIGNATION', name: 'CEO', code: 'CEO', sortOrder: 1 },
  { categoryKey: 'DESIGNATION', name: 'Manager', code: 'MANAGER', sortOrder: 2 },
  { categoryKey: 'DESIGNATION', name: 'Counsellor', code: 'COUNSELLOR', sortOrder: 3 },
  { categoryKey: 'DESIGNATION', name: 'Call Executive', code: 'CALL_EXECUTIVE', sortOrder: 4 },
  { categoryKey: 'DESIGNATION', name: 'Team Lead', code: 'TEAM_LEAD', sortOrder: 5 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Full-time', code: 'FULL_TIME', sortOrder: 1 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Part-time', code: 'PART_TIME', sortOrder: 2 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Contract', code: 'CONTRACT', sortOrder: 3 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Active', code: 'ACTIVE', sortOrder: 1 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'On Leave', code: 'ON_LEAVE', sortOrder: 2 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Inactive', code: 'INACTIVE', sortOrder: 3 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Resigned', code: 'RESIGNED', sortOrder: 4 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Academic', code: 'ACADEMIC', sortOrder: 1 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Financial', code: 'FINANCIAL', sortOrder: 2 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Personal', code: 'PERSONAL', sortOrder: 3 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Language', code: 'LANGUAGE', sortOrder: 4 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Application', code: 'APPLICATION', sortOrder: 5 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Other', code: 'OTHER', sortOrder: 6 },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Transcript', code: 'TRANSCRIPT', sortOrder: 1, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Degree Certificate', code: 'DEGREE', sortOrder: 2, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Bank Statement', code: 'BANK_STATEMENT', sortOrder: 3, parentCode: 'FINANCIAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Passport', code: 'PASSPORT', sortOrder: 4, parentCode: 'PERSONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'IELTS Scorecard', code: 'IELTS', sortOrder: 5, parentCode: 'LANGUAGE' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Offer Letter', code: 'OFFER', sortOrder: 6, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Pending', code: 'PENDING', sortOrder: 1 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Verified', code: 'VERIFIED', sortOrder: 2 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Rejected', code: 'REJECTED', sortOrder: 3 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Expired', code: 'EXPIRED', sortOrder: 4 },
  { categoryKey: 'REJECTION_REASON', name: 'Unclear Scan', code: 'UNCLEAR', sortOrder: 1 },
  { categoryKey: 'REJECTION_REASON', name: 'Expired Document', code: 'EXPIRED', sortOrder: 2 },
  { categoryKey: 'REJECTION_REASON', name: 'Name Mismatch', code: 'NAME_MISMATCH', sortOrder: 3 },
  { categoryKey: 'REJECTION_REASON', name: 'Incomplete Document', code: 'INCOMPLETE', sortOrder: 4 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Cash', code: 'CASH', sortOrder: 1 },
  { categoryKey: 'PAYMENT_METHOD', name: 'bKash', code: 'BKASH', sortOrder: 2 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Nagad', code: 'NAGAD', sortOrder: 3 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Bank Transfer', code: 'BANK', sortOrder: 4 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Card', code: 'CARD', sortOrder: 5 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Online Payment', code: 'ONLINE', sortOrder: 6 },
  { categoryKey: 'PAYMENT_TYPE', name: 'File Opening Charge', code: 'FILE_OPENING', sortOrder: 1 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Service Charge', code: 'SERVICE', sortOrder: 2 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Additional Service', code: 'ADDITIONAL', sortOrder: 3 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Custom Charge', code: 'CUSTOM', sortOrder: 4 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Pending', code: 'PENDING', sortOrder: 1 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Paid', code: 'PAID', sortOrder: 2 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Partial', code: 'PARTIAL', sortOrder: 3 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Refunded', code: 'REFUNDED', sortOrder: 4 },
  { categoryKey: 'REFUND_REASON', name: 'Service Cancelled', code: 'CANCELLED', sortOrder: 1 },
  { categoryKey: 'REFUND_REASON', name: 'Duplicate Payment', code: 'DUPLICATE', sortOrder: 2 },
  { categoryKey: 'REFUND_REASON', name: 'Overpayment', code: 'OVERPAYMENT', sortOrder: 3 },
]

export function getMasterDataCategory(key: string) {
  return MASTER_DATA_CATEGORY_MAP.get(key)
}
